// flow-typed signature: 5c40974da2afeb3f500471a8794195af
// flow-typed version: <<STUB>>/deep-eql_v3.0.1/flow_v0.80.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'deep-eql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'deep-eql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'deep-eql/deep-eql' {
  declare module.exports: any;
}

// Filename aliases
declare module 'deep-eql/deep-eql.js' {
  declare module.exports: $Exports<'deep-eql/deep-eql'>;
}
declare module 'deep-eql/index' {
  declare module.exports: $Exports<'deep-eql'>;
}
declare module 'deep-eql/index.js' {
  declare module.exports: $Exports<'deep-eql'>;
}
